# -----------------------------------------------------------------------------
# ezy-image-worker Runtime Validation
# -----------------------------------------------------------------------------

FROM pytorch/pytorch:2.7.1-cuda12.8-cudnn9-runtime

WORKDIR /app

ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1

COPY docker/requirements.runtime.txt /tmp/requirements.txt

RUN pip install --upgrade pip

RUN pip install -r /tmp/requirements.txt

COPY . .

CMD ["python", "-m", "app.handler"]